name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama que uses para el despliegue

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Asegura permisos de escritura para el contenido del repositorio
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject API Key
        run: echo "window.__HUBSPOT_API_KEY__ = '${{ secrets.HUBSPOT_API_KEY }}';" > api-key.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Publica desde el directorio raíz si usas GitHub Pages directamente desde el repositorio
